### ISSUE TITLE
Not finding subspecs with YAML based repo

### ISSUE THREAD

**Issue by orta** [CocoaPods/CocoaPods#1057]
I've been getting 

```
[!] Unable to find a specification named `ARAnalytics/TestFlight` in `ARAnalytics (1.3.1)`.
```

when doing a pod install with `cocoapods-0.19.1` - I've gone and taken a look inside `~/.cocoapods/Specs` which is currently checked out to the branch `yaml_podspecs`  and below is an excerpt from ARAnalytics 1.3.1 which seems to correctly refer to the subspec. Finally, I've included the code from my podfile to load it at the bottom. Any ideas?

```

---
name: ARAnalytics
version: 1.3.1
license:
  type: MIT
  file: LICENSE
summary: Use mutliple major analytics platforms with one clean API.
homepage: http://github.com/orta/ARAnalytics
authors:
  orta: orta.therox@gmail.com
source:
  git: https://github.com/orta/ARAnalytics.git
  tag: 1.3.1
description: Using subspecs you can define your analytics provider with the same API.
platforms:
  ios: 
subspecs:
- name: Core
  source_files:
  - '*.{h,m}'
  - Providers/ARAnalyticalProvider.{h,m}
  - Providers/ARAnalyticsProviders.h
- name: TestFlight
  dependencies:
    ARAnalytics/Core: []
    TestFlightSDK: []
    BPXLUUIDHandler: []
  prefix_header_contents: '#define AR_TESTFLIGHT_EXISTS 1'
  source_files:
  - Providers/TestFlightProvider.{h,m}
```

```
pod 'ARAnalytics/TestFlight', '~> 1.3'
pod 'ARAnalytics/Mixpanel', '~> 1.3'
pod 'ARAnalytics/Crashlytics', '~> 1.3'
```
