### ISSUE TITLE
[Bug] compute the cache about `incremental_installation` for 1.7.0.beta3

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#8657]
I test the `incremental_installation` in my project. But I found that there are some pod targets always be `Regenerating`.

I don't know why the cache does not work. So I debug the code, and I found that the YAML force use the `downcase` when YAML try to sort the array.

The `installation_cache.yaml`:
```
  AWEVideoFeed-b583dabf:
    BUILD_SETTINGS_CHECKSUM:
      AWEVideoFeed-b583dabf: 70d2e833e159805a67a68ee07012e312
    CHECKSUM: 3df9b79bd1c7543473679c40b930c525a61716cc
    SPECS:
      - AWEVideoFeed/ModuleInterface (0.1.0)
      - AWEVideoFeed/ModuleInterface/Interface (0.1.0)
      - AWEVideoFeed/ModuleInterface/Model (0.1.0)
      - AWEVideoFeed/MUS (0.1.0)
```

The `MUS` is the last one in the `SPECS`, it is because the `when String then value.downcase` of `sorting_string` in the `yaml_helper.rb`.
But the `MUS` is the first one when the target generate the cache key: `'SPECS' => pod_target.specs.map(&:to_s).sort`.

It is the why the cache does not work: the `SPCES` always be different.
