### ISSUE TITLE
The absolute path in metadata_cache.yaml will crash after move the workspace.

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#9440]
Use CocoaPods v1.7.5, I have a workspace at `/Users/xx/Applog`, and it works. After move the workspace to another directory, cocoapods will crash:

```
Errno::ENOENT - No such file or directory @ realpath_rec - /Users/xx/Applog
/Users/xx/.bundle/vendor/gems/cocoapods-1.7.5/lib/cocoapods/project.rb:320:in `realpath'
/Users/xx/.bundle/vendor/gems/cocoapods-1.7.5/lib/cocoapods/project.rb:320:in `realpath'
/Users/xx/.bundle/vendor/gems/cocoapods-1.7.5/lib/cocoapods/project.rb:320:in `reference_for_path'
/Users/xx/.bundle/vendor/gems/cocoapods-1.7.5/lib/cocoapods/project.rb:506:in `new_subproject_file_reference'
/Users/xx/.bundle/vendor/gems/cocoapods-1.7.5/lib/cocoapods/project.rb:303:in `add_cached_subproject_reference'
/Users/xx/.bundle/vendor/gems/cocoapods-1.7.5/lib/cocoapods/project.rb:164:in `add_cached_pod_subproject'
```

I check the `Pods/project_cache/metadata_cache.yaml`, I found that the `PROJECT_PATH`s are absolute paths, is it a bug?

**Comment by dnkoutso** [comment]
Hm yes we can probably change that . to be a relative path? cc @sebastianv1

**Comment by amorde** [comment]
Can you share some details of your project structure, and if possible your `yaml` cache files?

On a quick test project, I don't see any absolute paths in the metadata cache:

```yaml
CryptoSwift:
  LABEL: CryptoSwift
  PROJECT_PATH: CryptoSwift.xcodeproj
  UUID: 4E1375FA494E41BCCDD9424A50665074
GoogleMaps:
  LABEL: GoogleMaps
  PROJECT_PATH: GoogleMaps.xcodeproj
  UUID: BF08434370CEBD287CA17CA7862D7C59
GooglePlaces:
  LABEL: GooglePlaces
  PROJECT_PATH: GooglePlaces.xcodeproj
  UUID: 53B76E42A392C26A99A639ADAD740683
Pods-ArchitectureExample:
  LABEL: Pods-ArchitectureExample
  PROJECT_PATH: Pods.xcodeproj
  UUID: 34CE8200E45A902CB69EE27705E58768
RxSwift:
  LABEL: RxSwift
  PROJECT_PATH: RxSwift.xcodeproj
  UUID: F0179EE061353B7A322F596E97844774
```
